module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  auto_entitylabel: 0
  automated_cron: 0
  block: 0
  block_class: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  coffee: 0
  color: 0
  comment: 0
  conditional_fields: 0
  config: 0
  config_direct_save: 0
  config_update: 0
  contact: 0
  contentimport: 0
  contextual: 0
  ctools: 0
  ctools_block: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity: 0
  entity_browser: 0
  entity_browser_example: 0
  entity_embed: 0
  entity_reference_revisions: 0
  entityconnect: 0
  features: 0
  features_ui: 0
  field: 0
  field_collection: 0
  field_formatter_class: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  force_password_change: 0
  google_analytics: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  kint: 0
  layout_discovery: 0
  link: 0
  masquerade: 0
  masquerade_float_block: 0
  media_entity: 0
  media_entity_browser: 0
  media_entity_image: 0
  menu_per_role: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  page_manager: 0
  page_manager_ui: 0
  panels: 0
  paragraphs: 0
  path: 0
  pathauto: 0
  prlp: 0
  quickedit: 0
  rabbit_hole: 0
  rdf: 0
  redirect: 0
  redirect_404: 0
  rewrite_field: 0
  rh_media: 0
  rh_node: 0
  rh_taxonomy: 0
  rh_user: 0
  rules: 0
  search: 0
  shortcut: 0
  simple_block: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  toolbar_menu: 0
  total_control: 0
  tour: 0
  twig_field_value: 0
  twig_tweak: 0
  typed_data: 0
  update: 0
  user: 0
  views_conditional: 0
  views_field_view: 0
  views_ui: 0
  viewsreference: 0
  weight: 0
  extlink: 1
  menu_link_content: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  adminimal_theme: 0
  mo_m: 0
  cog: 0
  mom: 0
  elevenfeat: 0
  eleven: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
